# Generated by Django 5.0.2 on 2024-06-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_workspace_city_workspace_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="location",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="rules",
            field=models.TextField(blank=True, null=True),
        ),
    ]
