# Generated by Django 5.0.6 on 2024-06-29 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0001_initial"),
        ("workspaces", "0003_workspace_location_workspace_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="owner",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="owner.owner"
            ),
        ),
    ]
