# Generated by Django 5.0.6 on 2024-06-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0005_alter_workspace_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
