# Generated by Django 5.0.2 on 2024-06-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0011_remove_resource_workspace"),
        ("workspaces", "0006_workspace_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="resources",
            field=models.ManyToManyField(to="resources.resource"),
        ),
    ]
