# Generated by Django 5.0.6 on 2024-06-29 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
        ("resources", "0003_alter_resourcereservation_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourcereservation",
            name="user",
        ),
        migrations.AddField(
            model_name="resourcereservation",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
            ),
        ),
    ]
