# Generated by Django 5.0.2 on 2024-06-29 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
        ("resources", "0005_resource_workspace"),
        ("workspaces", "0004_workspace_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="workspace",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="workspaces.workspace"
            ),
        ),
        migrations.AlterField(
            model_name="resourcereservation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customer.customer"
            ),
        ),
    ]
