# Generated by Django 5.0.2 on 2024-06-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0006_alter_resource_workspace_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcereservation",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
