# Generated by Django 5.0.6 on 2024-06-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0008_resourcereservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
