# Generated by Django 5.0.2 on 2024-06-29 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0009_alter_resource_quantity"),
        ("workspaces", "0006_workspace_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="workspaces.workspace"
            ),
        ),
    ]
