# Generated by Django 5.0.2 on 2024-06-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0010_alter_resource_workspace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="workspace",
        ),
    ]
