# Generated by Django 5.0.2 on 2024-06-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0011_remove_resource_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
